export const MOOD = {
  "gibun-choego": {
    mood: "기분 최고",
    label: "오늘따라 기분이 참 좋아.\n뭔가 다 잘 풀릴 것 같아.",
    emoji: "😄",
    avatar: "../assets/images/gibun-choego.png",
    genre: "케이팝",
  },
  "jajang-na": {
    mood: "짜증 나",
    label: "작은 일에도 자꾸 예민해져.\n마음이 불편해.",
    emoji: "😠",
    avatar: "../assets/images/jajang-na.png",
    genre: "빡센 국힙",
  },
  "gopjang-dae": {
    mood: "걱정 돼",
    label: "걱정되는 일들이 자꾸만 떠올라.\n마음이 무거워.",
    emoji: "🥺",
    avatar: "../assets/images/gopjang-dae.png",
    genre: "인디 밴드",
  },
  "pigon-hae": {
    mood: "피곤해",
    label: "몸도 마음도 지쳤어.\n잠시 쉬고 싶어.",
    emoji: "😴",
    avatar: "../assets/images/pigon-hae.png",
    genre: "위로",
  },
  "geojye-geurae": {
    mood: "그저 그래",
    label: "딱히 좋지도 나쁘지도 않아.\n그냥 그런 날이야.",
    emoji: "😐",
    avatar: "../assets/images/geojye-geurae.png",
    genre: "신나는 아이돌 노래",
  },
  "wanbeop-johae": {
    mood: "완벽해!",
    label: "모든 게 딱 좋아.\n오늘은 참 평온하고 만족스러워.",
    emoji: "😊",
    avatar: "../assets/images/wanbeop-johae.png",
    genre: "popsong",
  },
  seolle: {
    mood: "설레",
    label: "마음이 조금 들떠.\n좋은 일이 생길 것 같아.",
    emoji: "💓",
    avatar: "../assets/images/seolle.png",
    genre: "연애 노래",
  },
  "uul-bohye": {
    mood: "우울해",
    label: "괜히 마음이 가라앉아.\n아무것도 손에 안 잡혀.",
    emoji: "😔",
    avatar: "../assets/images/uul-bohye.png",
    genre: "싱잉랩",
  },
};
